# ============================================================
# KOHLI HOSTING + PREDICTION BOT — AUTO OWNER v4.0
# ============================================================

import telebot
import threading
import time
import random
import pytz
import json
import os
from datetime import datetime
from telebot import types
from flask import Flask, request, jsonify

# ============================================================
# 🔧 MAIN CONFIG
# ============================================================
HOST_BOT_TOKEN = "8372270378:AAEXNRXUD2xTwShxB7z7WR5uqX2NrWBvN6o"
ADMIN_ID = 7741897793

bot = telebot.TeleBot(HOST_BOT_TOKEN, parse_mode="Markdown")

# ============================================================
# 🌐 GLOBAL STORAGE
# ============================================================
awaiting_token_from = set()
hosted_bots = {}   # {owner_id: {hosted_id: entry}}
hosted_by_id = {}  # {hosted_id: entry}  <-- lookup by hosted_id

# ============================================================
# 🔮 PREDICTION ENGINE
# ============================================================
def generate_prediction():
    num = random.randint(0, 9)
    if num >= 5:
        big_small = "🔴 BIG"
        image = "https://i.postimg.cc/VL8z327L/IMG-20250908-115951-469.jpg"
    else:
        big_small = "🔵 SMALL"
        image = "https://i.postimg.cc/FzthF6Np/IMG-20250908-115954-296.jpg"
    return big_small, num, image


def get_period_number():
    ist = pytz.timezone("Asia/Kolkata")
    now = datetime.now(ist)
    yyyyMMdd = now.strftime("%Y%m%d")
    total_minutes = now.hour * 60 + now.minute
    return f"{yyyyMMdd}1000{10001 + total_minutes}"


def get_remaining_seconds():
    ist = pytz.timezone("Asia/Kolkata")
    now = datetime.now(ist)
    return 60 - now.second if now.second < 60 else 0


def send_prediction(bot_obj, chat_id, period, big_small, num, image):
    caption = f"""
🎯 KOHLI AI Prediction
━━━━━━━━━━━━━━━━━━━
🧾 Period: {period}
🧩 Prediction: {big_small} – {num}
⏱ Next: 1 Minute
━━━━━━━━━━━━━━━━━━━
⚡ Auto-generated by BDG AI Engine
"""
    try:
        bot_obj.send_photo(chat_id, image, caption=caption)
    except Exception as e:
        print(f"[!] Prediction send failed: {e}")


# ============================================================
# 📊 USER STATS
# ============================================================
def load_users(file_path):
    if not os.path.exists(file_path):
        return {}
    with open(file_path, "r") as f:
        try:
            return json.load(f)
        except:
            return {}


def save_users(file_path, data):
    with open(file_path, "w") as f:
        json.dump(data, f, indent=2)


def update_user_stats(user_id, file_path):
    users = load_users(file_path)
    now = datetime.now().strftime("%Y-%m-%d")
    if str(user_id) not in users:
        users[str(user_id)] = {"first_seen": now, "last_seen": now, "usage_count": 1}
    else:
        users[str(user_id)]["last_seen"] = now
        users[str(user_id)]["usage_count"] += 1
    save_users(file_path, users)


def get_stats(file_path):
    users = load_users(file_path)
    today = datetime.now()
    day1, day2 = 0, 0
    top_users = sorted(users.items(), key=lambda x: x[1]["usage_count"], reverse=True)
    for u in users.values():
        try:
            last = datetime.strptime(u["last_seen"], "%Y-%m-%d")
            delta = (today - last).days
            if delta == 0:
                day1 += 1
            elif delta == 1:
                day2 += 1
        except:
            pass
    top_list = "\n".join(
        [f"👤 {uid} — {info['usage_count']} uses" for uid, info in top_users[:5]]
    ) or "No users yet."
    return len(users), day1, day2, top_list


# ============================================================
# 🧠 HOSTED PREDICTION BOT (WITH AUTO OWNER)
# ============================================================
def start_hosted_prediction_bot(token, initial_owner, hosted_id):
    try:
        hosted = telebot.TeleBot(token, parse_mode="Markdown")
        me = hosted.get_me()
    except Exception as e:
        raise RuntimeError(f"❌ Invalid Token: {e}")

    active_dict = {}
    user_channels = {}
    user_file = f"users_{me.id}.json"
    owner_file = f"owner_{hosted_id}.txt"
    runtime = {"paused": False}

    # ✅ Determine current owner
    current_owner = {"id": initial_owner}

    # Check if owner file exists
    if os.path.exists(owner_file):
        try:
            with open(owner_file, "r") as f:
                saved = f.read().strip()
                if saved:
                    current_owner["id"] = int(saved)
        except:
            pass

    def save_owner(uid):
        try:
            with open(owner_file, "w") as f:
                f.write(str(uid))
            current_owner["id"] = uid
            # Register in hosted_bots
            hosted_bots.setdefault(uid, {})[hosted_id] = _entry_ref[0]
            print(f"[OWNER] Bot {me.username} owner set to {uid}")
        except Exception as e:
            print(f"[OWNER] Save failed: {e}")

    def get_owner():
        return current_owner["id"]

    # Placeholder for entry ref
    _entry_ref = [None]

    def start_prediction_cycle(bot_obj, chat_id, channel_id=None):
        last_period = None
        while active_dict.get(chat_id):
            if runtime["paused"]:
                time.sleep(2)
                continue
            period = get_period_number()
            if period != last_period:
                big_small, num, image = generate_prediction()
                send_prediction(bot_obj, chat_id, period, big_small, num, image)
                if channel_id:
                    send_prediction(bot_obj, channel_id, period, big_small, num, image)
                last_period = period
            for _ in range(get_remaining_seconds(), 0, -1):
                if not active_dict.get(chat_id):
                    break
                time.sleep(1)

    def create_prediction_menu():
        kb = types.ReplyKeyboardMarkup(resize_keyboard=True)
        kb.row("🧠 Start Prediction", "🛑 Stop Prediction")
        kb.row("📢 Set Channel", "📊 Stats")
        kb.row("👑 Developer")
        return kb

    @hosted.message_handler(commands=["start"])
    def start(msg):
        # ✅ AUTO OWNER: First user becomes owner
        if not os.path.exists(owner_file) or not current_owner["id"]:
            save_owner(msg.from_user.id)
        
        update_user_stats(msg.from_user.id, user_file)
        kb = create_prediction_menu()
        hosted.send_message(
            msg.chat.id,
            f"🤖 *Welcome to {me.first_name}'s Prediction Bot*\n\n"
            f"💡 Get 1-minute Wingo Predictions + Channel Auto Post.\n"
            f"Use the buttons below 👇",
            reply_markup=kb,
        )

    @hosted.message_handler(func=lambda m: True)
    def buttons(msg):
        text = msg.text
        cid = msg.chat.id
        update_user_stats(cid, user_file)

        if text == "🧠 Start Prediction":
            if active_dict.get(cid):
                hosted.send_message(cid, "⚠️ Already running.",
                                    reply_markup=create_prediction_menu())
                return
            active_dict[cid] = True
            runtime["paused"] = False
            ch = user_channels.get(cid)
            hosted.send_message(
                cid,
                "✅ Prediction started.\n"
                f"{'📢 Channel: ' + str(ch) if ch else 'No channel linked.'}",
                reply_markup=create_prediction_menu(),
            )
            threading.Thread(
                target=start_prediction_cycle,
                args=(hosted, cid, ch),
                daemon=True,
            ).start()

        elif text == "🛑 Stop Prediction":
            active_dict[cid] = False
            hosted.send_message(cid, "🛑 Stopped.",
                                reply_markup=create_prediction_menu())

        elif text == "📢 Set Channel":
            hosted.send_message(
                cid,
                "📢 Send your *channel username* (like `@yourchannel`).\n"
                "⚠️ Make sure bot is *admin* there.",
                parse_mode="Markdown",
            )
            user_channels[cid] = "waiting"

        elif text == "📊 Stats":
            total, d1, d2, top = get_stats(user_file)
            hosted.send_message(
                cid,
                f"📊 *Bot Statistics*\n━━━━━━━━━━━━━━━\n"
                f"👥 Total: *{total}*\n"
                f"📅 Today: *{d1}*\n"
                f"📅 Yesterday: *{d2}*\n\n"
                f"🏆 *Top:*\n{top}",
                parse_mode="Markdown",
                reply_markup=create_prediction_menu(),
            )

        elif text == "👑 Developer":
            markup = types.InlineKeyboardMarkup()
            markup.add(types.InlineKeyboardButton("💬 Message",
                                                  url="https://t.me/xxLEGEND_KOHLI"))
            hosted.send_message(cid, "👑 Developer:", reply_markup=markup)

        elif user_channels.get(cid) == "waiting":
            channel_input = text.strip()
            try:
                hosted.send_message(channel_input, "✅ Channel linked!")
                user_channels[cid] = channel_input
                hosted.send_message(
                    cid,
                    f"✅ Linked: `{channel_input}`",
                    parse_mode="Markdown",
                    reply_markup=create_prediction_menu(),
                )
            except Exception as e:
                hosted.send_message(cid, f"❌ Failed: {e}",
                                    reply_markup=create_prediction_menu())
                user_channels[cid] = None

    def run_bot():
        try:
            hosted.infinity_polling(timeout=60, long_polling_timeout=60)
        except Exception as e:
            print(f"[!] Bot {me.username} stopped: {e}")

    thread = threading.Thread(target=run_bot, daemon=True)
    thread.start()

    entry = {
        "token": token,
        "thread": thread,
        "info": {"username": me.username, "id": me.id},
        "running": True,
        "runtime": runtime,
        "hosted_id": hosted_id,
        "owner_file": owner_file,
        "get_owner": get_owner,
    }
    _entry_ref[0] = entry

    # Save to hosted_by_id for lookup
    hosted_by_id[hosted_id] = entry
    if initial_owner:
        hosted_bots.setdefault(initial_owner, {})[hosted_id] = entry

    return entry


# ============================================================
# 🌐 FLASK API
# ============================================================
api_app = Flask(__name__)


@api_app.route("/", methods=["GET"])
def home():
    return jsonify({
        "status": "ok",
        "message": "KOHLI Bot Hosting Server Running",
        "hosted_bots": sum(len(b) for b in hosted_bots.values())
    })


# ---------- CREATE BOT (SIRF TOKEN) ----------
@api_app.route("/api/create_bot", methods=["POST"])
def api_create_bot():
    try:
        data = request.get_json() or {}
        token = (data.get("token") or "").strip()

        if not token or ":" not in token or len(token) < 30:
            return jsonify({
                "status": "error",
                "message": "Invalid bot token format"
            }), 400

        # Duplicate check
        for hid, e in hosted_by_id.items():
            if e.get("token") == token:
                return jsonify({
                    "status": "ok",
                    "username": e["info"]["username"],
                    "bot_id": e["info"]["id"],
                    "hosted_id": hid,
                    "message": "Bot already running"
                })

        # Start with no owner (will auto-set on /start)
        hosted_id = f"bot_{int(time.time())}_{random.randint(1000,9999)}"
        entry = start_hosted_prediction_bot(token, None, hosted_id)

        # Notify admin
        try:
            bot.send_message(
                ADMIN_ID,
                f"🔑 *New Bot Created*\n\n"
                f"🤖 Bot: @{entry['info']['username']}\n"
                f"🆔 ID: `{entry['info']['id']}`\n"
                f"📦 Hosted ID: `{hosted_id}`\n\n"
                f"⚠️ Owner will be set when someone presses /start",
                parse_mode="Markdown"
            )
        except Exception as e:
            print(f"[!] Admin notify failed: {e}")

        return jsonify({
            "status": "ok",
            "username": entry["info"]["username"],
            "bot_id": entry["info"]["id"],
            "hosted_id": hosted_id,
            "message": "Bot created successfully"
        })

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ---------- LIST BOTS (by owner who /start'd their own bot) ----------
@api_app.route("/api/list_bots", methods=["POST"])
def api_list_bots():
    try:
        data = request.get_json() or {}
        owner_id = str(data.get("owner_id") or "").strip()

        if not owner_id or not owner_id.lstrip("-").isdigit():
            return jsonify({"status": "error", "message": "Invalid owner"}), 400

        owner_int = int(owner_id)

        # ✅ Find all bots where this user is owner
        # Includes hosted_bots[owner] AND owner_file checks
        result = []
        seen = set()

        # From hosted_bots
        for hid, entry in hosted_bots.get(owner_int, {}).items():
            if hid not in seen:
                seen.add(hid)
                result.append({
                    "username": entry["info"]["username"],
                    "bot_id": str(entry["info"]["id"]),
                    "hosted_id": str(hid),
                    "running": entry.get("running", True)
                })

        # From owner_file scan (for safety)
        for hid, entry in hosted_by_id.items():
            if hid in seen:
                continue
            owner_file = entry.get("owner_file")
            if owner_file and os.path.exists(owner_file):
                try:
                    with open(owner_file, "r") as f:
                        if f.read().strip() == owner_id:
                            seen.add(hid)
                            result.append({
                                "username": entry["info"]["username"],
                                "bot_id": str(entry["info"]["id"]),
                                "hosted_id": str(hid),
                                "running": entry.get("running", True)
                            })
                except:
                    pass

        return jsonify({
            "status": "ok",
            "bots": result,
            "count": len(result)
        })

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ---------- TOGGLE ----------
@api_app.route("/api/toggle_bot", methods=["POST"])
def api_toggle_bot():
    try:
        data = request.get_json() or {}
        hosted_id = (data.get("hosted_id") or "").strip()
        action = (data.get("action") or "").strip().lower()

        if hosted_id not in hosted_by_id:
            return jsonify({"status": "error", "message": "Bot not found"}), 404

        entry = hosted_by_id[hosted_id]

        if action == "off":
            entry["running"] = False
            if "runtime" in entry:
                entry["runtime"]["paused"] = True
            return jsonify({"status": "ok", "running": False})
        elif action == "on":
            entry["running"] = True
            if "runtime" in entry:
                entry["runtime"]["paused"] = False
            return jsonify({"status": "ok", "running": True})
        else:
            return jsonify({"status": "error", "message": "Invalid action"}), 400

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ---------- DELETE ----------
@api_app.route("/api/delete_bot", methods=["POST"])
def api_delete_bot():
    try:
        data = request.get_json() or {}
        hosted_id = (data.get("hosted_id") or "").strip()

        if hosted_id not in hosted_by_id:
            return jsonify({"status": "error", "message": "Bot not found"}), 404

        entry = hosted_by_id[hosted_id]
        entry["running"] = False
        if "runtime" in entry:
            entry["runtime"]["paused"] = True

        # Remove from all storage
        del hosted_by_id[hosted_id]
        for uid, bots in hosted_bots.items():
            if hosted_id in bots:
                del bots[hosted_id]

        # Delete owner file
        owner_file = entry.get("owner_file")
        if owner_file and os.path.exists(owner_file):
            try:
                os.remove(owner_file)
            except:
                pass

        return jsonify({"status": "ok", "message": "Deleted"})

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ---------- BROADCAST ----------
@api_app.route("/api/broadcast", methods=["POST"])
def api_broadcast():
    try:
        data = request.get_json() or {}
        hosted_id = (data.get("hosted_id") or "").strip()
        message = (data.get("message") or "").strip()

        if hosted_id not in hosted_by_id:
            return jsonify({"status": "error", "message": "Bot not found"}), 404

        if not message:
            return jsonify({"status": "error", "message": "Empty message"}), 400

        entry = hosted_by_id[hosted_id]
        bot_id = entry["info"]["id"]
        token = entry.get("token")
        user_file = f"users_{bot_id}.json"
        users = load_users(user_file)

        if not users:
            return jsonify({"status": "ok", "sent": 0, "failed": 0})

        broadcast_bot = telebot.TeleBot(token, parse_mode="Markdown")
        sent = 0
        failed = 0

        for uid in list(users.keys()):
            try:
                broadcast_bot.send_message(
                    int(uid),
                    f"📢 *Broadcast*\n━━━━━━━━━━━━━━━\n\n{message}\n\n━━━━━━━━━━━━━━━",
                    parse_mode="Markdown"
                )
                sent += 1
                time.sleep(0.05)
            except Exception:
                failed += 1

        return jsonify({"status": "ok", "sent": sent, "failed": failed})

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ---------- STATS ----------
@api_app.route("/api/bot_stats", methods=["POST"])
def api_bot_stats():
    try:
        data = request.get_json() or {}
        hosted_id = (data.get("hosted_id") or "").strip()

        if hosted_id not in hosted_by_id:
            return jsonify({"status": "error", "message": "Bot not found"}), 404

        entry = hosted_by_id[hosted_id]
        bot_id = entry["info"]["id"]
        user_file = f"users_{bot_id}.json"
        total, d1, d2, _ = get_stats(user_file)

        return jsonify({
            "status": "ok",
            "total_users": total,
            "active_today": d1,
            "active_yesterday": d2,
            "running": entry.get("running", False),
            "username": entry["info"]["username"]
        })

    except Exception as e:
        return jsonify({"status": "error", "message": str(e)}), 500


# ============================================================
# 🚀 RUN
# ============================================================
def run_api():
    port = int(os.environ.get("PORT", 5000))
    api_app.run(host="0.0.0.0", port=port, debug=False, use_reloader=False)


if __name__ == "__main__":
    threading.Thread(target=run_api, daemon=True).start()
    print("🚀 KOHLI Hosting Bot running...")
    while True:
        try:
            bot.infinity_polling(timeout=60, long_polling_timeout=60)
        except Exception as e:
            print(f"[!] Bot crash: {e}")
            time.sleep(5)
